2019-04-26 16:06:23,393 - selenium.webdriver.remote.remote_connection - INFO - Could not connect to port 4723 on host localhost
2019-04-26 16:06:23,393 - selenium.webdriver.remote.remote_connection - INFO - Could not get IP address for host: localhost
2019-04-26 16:06:25,423 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000004A012B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-04-26 16:06:27,453 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000004A01470>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-04-26 16:06:29,484 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000004A01588>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-04-26 16:06:33,515 - selenium.webdriver.remote.remote_connection - INFO - Could not connect to port 4723 on host localhost
2019-04-26 16:06:33,515 - selenium.webdriver.remote.remote_connection - INFO - Could not get IP address for host: localhost
2019-04-26 16:06:35,551 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000004A01978>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-04-26 16:06:37,594 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000004A01B38>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-04-26 16:06:39,624 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000004A01C50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-04-26 16:06:43,670 - selenium.webdriver.remote.remote_connection - INFO - Could not connect to port 4723 on host localhost
2019-04-26 16:06:43,670 - selenium.webdriver.remote.remote_connection - INFO - Could not get IP address for host: localhost
2019-04-26 16:06:45,683 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000004A15128>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-04-26 16:06:47,709 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000004A152E8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-04-26 16:07:08,210 - root - INFO - PASS设备已经启动,wait5
2019-04-26 16:07:16,830 - root - INFO - PASSleft
2019-04-26 16:07:25,859 - root - INFO - FAILMessage: An unknown server-side error occurred while processing the command. Original error: Swipe did not complete successfully

